name: API Rest tests

on:
  push:
   pull_request:
   workflow_dispatch:

jobs:
  cypress-run:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        