name: API Rest tests

on:
  push:
   pull_request:
   workflow_dispatch:

jobs:
  cypress-run:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2 

      - name: Run App & Cypress
        run: |
          yarn ci-start & # run app in background
          npx -y wait-on DOMAIN_OF_APP --timeout 300000 &&
          yarn cypress:ci
        
         